GET http://0.0.0.0:5000/kitty/
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTYyZDAyNTJlYzU4NTBlZDM4ZmU0YWUiLCJleHAiOjE2MzM4ODkwMDE1NjQsImlhdCI6MTYzMzg4ODk5N30.OBuUQrcqBI3e_qo8lgfDmZTiRFaQLIpIntXOmUIYZxs
