GET http://0.0.0.0:5000/kitty/
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmQ4MzJmYjMzZThjOTYwMTY5NDQ0NDkiLCJleHBpcmVzSW4iOiIyNGgiLCJpYXQiOjE2NTgzMzY4NzJ9.unZNsfOuQJiNd6x_iELDphlVZA5ZznUB5K3DnsdAnPk
